// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ControleEmprestimo.DATA.Models
{
    public partial class Emprestimo
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idProduto")]
        public int? IdProduto { get; set; }
        [Column("idPessoa")]
        public int? IdPessoa { get; set; }
        [Column("dataEmprestimo", TypeName = "datetime")]
        public DateTime? DataEmprestimo { get; set; }
        [Column("dataEntrega", TypeName = "datetime")]
        public DateTime? DataEntrega { get; set; }
        [Column("entregue")]
        public bool? Entregue { get; set; }

        [ForeignKey("IdPessoa")]
        [InverseProperty("Emprestimo")]
        public virtual Pessoa IdPessoaNavigation { get; set; }
        [ForeignKey("IdProduto")]
        [InverseProperty("Emprestimo")]
        public virtual Produto IdProdutoNavigation { get; set; }
    }
}