// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ControleEmprestimo.DATA.Models
{
    public partial class Pessoa
    {
        public Pessoa()
        {
            Emprestimo = new HashSet<Emprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Column("endereco")]
        [StringLength(200)]
        [Unicode(false)]
        public string Endereco { get; set; }
        [Column("bairro")]
        [StringLength(50)]
        [Unicode(false)]
        public string Bairro { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(50)]
        [Unicode(false)]
        public string Cidade { get; set; }
        [Required]
        [Column("tel")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tel { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }

        [InverseProperty("IdPessoaNavigation")]
        public virtual ICollection<Emprestimo> Emprestimo { get; set; }
    }
}