// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ControleEmprestimo.DATA.Models
{
    public partial class Produto
    {
        public Produto()
        {
            Emprestimo = new HashSet<Emprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nome { get; set; }
        [Required]
        [Column("categoria")]
        [StringLength(50)]
        [Unicode(false)]
        public string Categoria { get; set; }
        [Column("obs")]
        [StringLength(200)]
        [Unicode(false)]
        public string Obs { get; set; }

        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<Emprestimo> Emprestimo { get; set; }
    }
}